[23.08.2019 21:51:40]
System.InvalidOperationException: Из удаленной конечной точки уже получен закрывающий кадр.
   в System.Web.WebSockets.AspNetWebSocket.ThrowIfReceiveUnavailable(Boolean allowClosed)
   в System.Web.WebSockets.AspNetWebSocket.ReceiveAsyncImpl(ArraySegment`1 buffer, CancellationToken cancellationToken, Boolean performValidation)
   в System.Web.WebSockets.AspNetWebSocket.ReceiveAsync(ArraySegment`1 buffer, CancellationToken cancellationToken)
   в WS.WSService.RTCTest.<ReceiveData>d__16.MoveNext() в C:\Users\softc\Documents\Visual Studio 2017\Projects\WS_gh\WS_RTC\WSService\RTCTest.cs:строка 174
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в WS.WSService.RTCTest.<CommunicateWithClient>d__12.MoveNext() в C:\Users\softc\Documents\Visual Studio 2017\Projects\WS_gh\WS_RTC\WSService\RTCTest.cs:строка 110
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   в WS.WSService.RTCTest.<ServeClient>d__13.MoveNext() в C:\Users\softc\Documents\Visual Studio 2017\Projects\WS_gh\WS_RTC\WSService\RTCTest.cs:строка 129
[23.08.2019 21:52:24]
System.InvalidOperationException: Из удаленной конечной точки уже получен закрывающий кадр.
   в System.Web.WebSockets.AspNetWebSocket.ThrowIfReceiveUnavailable(Boolean allowClosed)
   в System.Web.WebSockets.AspNetWebSocket.ReceiveAsyncImpl(ArraySegment`1 buffer, CancellationToken cancellationToken, Boolean performValidation)
   в System.Web.WebSockets.AspNetWebSocket.ReceiveAsync(ArraySegment`1 buffer, CancellationToken cancellationToken)
   в WS.WSService.RTCTest.<ReceiveData>d__16.MoveNext() в C:\Users\softc\Documents\Visual Studio 2017\Projects\WS_gh\WS_RTC\WSService\RTCTest.cs:строка 174
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в WS.WSService.RTCTest.<CommunicateWithClient>d__12.MoveNext() в C:\Users\softc\Documents\Visual Studio 2017\Projects\WS_gh\WS_RTC\WSService\RTCTest.cs:строка 110
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   в WS.WSService.RTCTest.<ServeClient>d__13.MoveNext() в C:\Users\softc\Documents\Visual Studio 2017\Projects\WS_gh\WS_RTC\WSService\RTCTest.cs:строка 129
[23.08.2019 21:57:37]
System.InvalidOperationException: Из удаленной конечной точки уже получен закрывающий кадр.
   в System.Web.WebSockets.AspNetWebSocket.ThrowIfReceiveUnavailable(Boolean allowClosed)
   в System.Web.WebSockets.AspNetWebSocket.ReceiveAsyncImpl(ArraySegment`1 buffer, CancellationToken cancellationToken, Boolean performValidation)
   в System.Web.WebSockets.AspNetWebSocket.ReceiveAsync(ArraySegment`1 buffer, CancellationToken cancellationToken)
   в WS.WSService.RTCTest.<ReceiveData>d__16.MoveNext() в C:\Users\softc\Documents\Visual Studio 2017\Projects\WS_gh\WS_RTC\WSService\RTCTest.cs:строка 174
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в WS.WSService.RTCTest.<CommunicateWithClient>d__12.MoveNext() в C:\Users\softc\Documents\Visual Studio 2017\Projects\WS_gh\WS_RTC\WSService\RTCTest.cs:строка 110
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   в WS.WSService.RTCTest.<ServeClient>d__13.MoveNext() в C:\Users\softc\Documents\Visual Studio 2017\Projects\WS_gh\WS_RTC\WSService\RTCTest.cs:строка 129

